#' Get subject areas from a set of publications
#'
#' Pass a data frame generated by get_researcher_data() into this function, and it
#' looks up the academic subject areas of the journals the research was published in.
#'
#' @param data data frame
#'
#' @return data frame with one column of field names obtained from Scopus
#' and one column of field frequencies
#' @export
#'
#' @examples
#' get_subject_areas(data)
#'
get_subject_areas <- function(data, apiKey) {

  #remove publications that don't have an associated ISSN values
  field <- data[!is.na(data[, "prism:issn"]),]

  #API call to retrieve journal information
  field <- lapply(field[["prism:issn"]],
                  function(x) httr::GET(
                    url = paste0("https://api.elsevier.com/content/serial/title/issn/",
                                 x),
                    query = list(apikey = apiKey,
                                 field="subject-area")))


  #parse the response
  field <- lapply(field,
                  function(x) jsonlite::fromJSON(
                    httr::content(x, "text")))

  #subset the data into a list containing only the subject area codes
  field <- lapply(field,
                  function(x) x[[1]][[2]][[2]][[1]])

  # bind the rows to a data frame
  field <- do.call(rbind, field)

  # creates a new data frame with field counts
  field <- as.data.frame(table(field[[4]]))

  return(field)
}
